siteTitle = "Timo Becker"
siteDescription = "Enthusiastic Berlin based illustrator, explorer and dad. Gladly illustrating books, magazines and events. Also developing concept art for your game or movie."
siteUrl = "https://timobecker.com"
linkPrefix = "/gatsby-starter-default"